-- 2022년 1월 도서 판매 데이터를 기준으로 저자 별, 카테고리 별 매출액을 구하라
-- 책별로 2022년 1월 도서 판매 매출액을 계산해보자
WITH T AS (
    SELECT B.BOOK_ID, (SUM(S.SALES) * B.PRICE) TOTAL_SALES
    FROM BOOK B
    JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
    WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
    GROUP BY B.BOOK_ID, B.PRICE
)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(T.TOTAL_SALES) TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN T
ON B.BOOK_ID = T.BOOK_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;