# 테이블 : BOOK, AUTHOR, BOOK_SALES
# 2022년 1월의 도서 판매 데이터를 기준으로 저자 별, 카테고리 별 매출액을 구해야 함.
WITH BS AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES_SUM
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%' 
    GROUP BY BOOK_ID
)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((BS.SALES_SUM * B.PRICE)) AS TOTAL_SALES
FROM BOOK B
INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BS ON B.BOOK_ID = BS.BOOK_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;

# SELECT *
# FROM BOOK

