-- 코드를 입력하세요
SELECT FI.FLAVOR 
FROM  FIRST_HALF AS FI LEFT JOIN ICECREAM_INFO AS IC ON FI.FLAVOR = IC.FLAVOR
WHERE FI.TOTAL_ORDER >= 3000 AND IC.INGREDIENT_TYPE = 'fruit_based'
ORDER BY FI.TOTAL_ORDER DESC;