-- 상품코드 별 매출액 합계 출력
SELECT P.PRODUCT_CODE, (SALES_SUM * P.PRICE) SALES
FROM PRODUCT P
JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SALES_SUM
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
    ) O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE;
