-- 2022년 3월의 오프라인/온라인 상품 판매 데이터
-- 판매 날짜, 상품 id, 유저 id, 판매량 출력
WITH A AS (
    SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-dd') SALES_DATE, PRODUCT_ID, USER_ID, SUM(SALES_AMOUNT) SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
    GROUP BY TO_CHAR(SALES_DATE, 'YYYY-MM-dd'), PRODUCT_ID, USER_ID
),

B AS (
    SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-dd') SALES_DATE, PRODUCT_ID, NULL USER_ID, SUM(SALES_AMOUNT) SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
    GROUP BY TO_CHAR(SALES_DATE, 'YYYY-MM-dd'), PRODUCT_ID
)

SELECT A.SALES_DATE SALES_DATE, A.PRODUCT_ID PRODUCT_ID, A.USER_ID USER_ID, A.SALES_AMOUNT
FROM A
UNION ALL
SELECT B.SALES_DATE, B.PRODUCT_ID, B.USER_ID, B.SALES_AMOUNT
FROM B
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;