-- 2022년 3월의 오프라인/온라인 상품 판매 데이터의 정보 출력
-- 
SELECT 
  TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE,
  PRODUCT_ID,
  USER_ID,
  SALES_AMOUNT
FROM ONLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203'
UNION ALL
SELECT 
  TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE,
  PRODUCT_ID,
  NULL USER_ID,
  SALES_AMOUNT
FROM OFFLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
