-- 대여해주는 자동차 정보 테이블, 대여 기록 정보 테이블, 자동차 종류 별 대여 기간 종류 별 할인 정책 정보 테이블
-- 자동차 종류가 '세단' 또는 'suv'인 자동차 중
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고
-- 30일간 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서
-- 자동차 Id, 자동차 종류, 대여 금액 리스트를 출력
WITH A AS (
    SELECT DISTINCT(CR.CAR_ID), CC.CAR_TYPE, CC.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CR
    JOIN CAR_RENTAL_COMPANY_CAR CC
    ON CR.CAR_ID = CC.CAR_ID
    WHERE CR.CAR_ID NOT IN (
        SELECT C.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
        WHERE (C.START_DATE < TO_DATE('2022-11-01', 'YYYY-MM-dd') and C.END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-dd')) OR
            (C.START_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-dd') and C.END_DATE >= C.START_DATE) 
    ) and (CC.CAR_TYPE = '세단' OR CC.CAR_TYPE = 'SUV')
), 

B AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
)

SELECT A.CAR_ID, A.CAR_TYPE, (A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) FEE
FROM A
JOIN B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE (A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) >= 500000 and
    (A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;
