-- 자동차 종류가 세단 또는 SUV인 자동차 중에서
-- 2022년 11월 1일 ~ 2022년 11월 30일까지 대여 가능하고
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 출력
-- FEE를 계산해야 됨.
WITH FT AS (
            SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, TRUNCATE((CRCC.DAILY_FEE * 30 * (1 - (CRCDP.DISCOUNT_RATE / 100))), 0) AS FEE
            FROM CAR_RENTAL_COMPANY_CAR CRCC INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
            ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
            WHERE CRCDP.DURATION_TYPE LIKE '30일 이상' AND (CRCC.CAR_TYPE = '세단' OR CRCC.CAR_TYPE = 'SUV')
)


SELECT DISTINCT(FT.CAR_ID), FT.CAR_TYPE, FT.FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH INNER JOIN FT 
ON CRCRH.CAR_ID = FT.CAR_ID
WHERE FT.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
AND (FEE BETWEEN 500000 AND 1999999)
ORDER BY FT.FEE DESC, FT.CAR_TYPE, FT.CAR_ID DESC