-- 코드를 입력하세요
WITH MF AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT REST_INFO.FOOD_TYPE, REST_INFO.REST_ID, REST_INFO.REST_NAME, MF.FAVORITES
FROM REST_INFO INNER JOIN MF
ON REST_INFO.FOOD_TYPE = MF.FOOD_TYPE
WHERE REST_INFO.FAVORITES = MF.FAVORITES
ORDER BY FOOD_TYPE DESC