-- 중고 거래 게시물을 3건 이상 등록한 사용자
SELECT 
  USER_ID, 
  NICKNAME, 
  CONCAT(CITY, CONCAT(' ', CONCAT(STREET_ADDRESS1, CONCAT(' ', STREET_ADDRESS2)))) "전체주소",
  SUBSTR(TLNO, 1, 3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8, 4) "전화번호"
FROM USED_GOODS_USER
WHERE USER_ID IN (
    SELECT B.WRITER_ID
    FROM USED_GOODS_BOARD B
    JOIN USED_GOODS_USER U
    ON B.WRITER_ID = U.USER_ID
    GROUP BY B.WRITER_ID
    HAVING COUNT(B.BOARD_ID) >= 3
)
ORDER BY USER_ID DESC;