-- 년,월,성별 별로 상품을 구매한 회원수를 집계
-- 성별 정보 없는 경우 결과에서 제외
SELECT TO_CHAR(O.SALES_DATE, 'YYYY') YEAR, TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) MONTH, U.GENDER, COUNT(DISTINCT(U.USER_ID)) USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), TO_CHAR(O.SALES_DATE, 'MM'), U.GENDER
ORDER BY YEAR, MONTH, U.GENDER;
