-- USER_INFO : 가입 회원 정보
-- ONLINE_SALE : 온라인 상품 판매 정보
-- 년, 월, 성별 별로 상품을 구매한 회원수 집계
SELECT 
  TO_CHAR(O.SALES_DATE, 'YYYY') YEAR, 
  TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) MONTH,
  U.GENDER,
  COUNT(DISTINCT(U.USER_ID)) USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), 
        TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')),
        U.GENDER
ORDER BY YEAR, MONTH, U.GENDER;
