# 년, 월, 성별 별로 상품을 구매한 회원수를 집계
# 성별 정보가 없는 경우 결과에서 제외
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, UI.GENDER, COUNT(DISTINCT(UI.USER_ID)) AS USERS
FROM USER_INFO UI INNER JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER;