# 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율을 년, 월, 별로 출력
# PUCHASED_USERS = 2021년에 가입한 전체 회원들 중 상품을 구매한 회원 수
# PUCHASED_RATIO = (2021년에 가입한 회원 중 상품을 구매한 회원수) / (2021년에 가입한 전체 회원수)


SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT(USER_ID)) PUCHASED_USERS,
ROUND((COUNT(DISTINCT(USER_ID))/(SELECT COUNT(DISTINCT(USER_ID)) AS '2021전체회원수' FROM USER_INFO WHERE JOINED LIKE '2021%')), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE '2021%')
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE);