-- 회원정보 테이블, 온라인 상품 판매 정보 테이블
-- 2021년에 가입한 전체 회원들 중
-- 상품을 구매한 회원수,  상품을 구매한 회원의 비율(상품 구매 회원 수 / 전체 회원 수)
-- 년 / 월 별로 출력

SELECT 
    TO_CHAR(O.SALES_DATE, 'YYYY') YEAR, 
    TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) MONTH,
    COUNT(DISTINCT(U.USER_ID)) PURCHASED_USERS,
    ROUND((COUNT(DISTINCT(U.USER_ID)) / (
        SELECT COUNT(USER_ID)
        FROM USER_INFO
        WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
    )), 1) PURCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE U.USER_ID IN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
)
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM'))
ORDER BY YEAR, MONTH;


