-- 
WITH A AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= TO_DATE('2022-10-16', 'YYYY-MM-dd') and 
       END_DATE >= TO_DATE('2022-10-16', 'YYYY-MM-dd')
)

SELECT 
    DISTINCT(C.CAR_ID), 
    CASE WHEN A.CAR_ID IS NULL THEN '대여 가능'
        ELSE '대여중' END AS AVAILABILITY
FROM A
RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C
ON A.CAR_ID = C.CAR_ID
ORDER BY C.CAR_ID DESC;


