-- 2022년 10월 16일에 대여 중인 자동차인 경우 '대여중' 표시, 아니면 '대여 가능' 표시
WITH AVAILABLE_CAR AS (
    SELECT DISTINCT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= TO_DATE('2022-10-16', 'YYYY-MM-DD') 
      AND END_DATE >= TO_DATE('2022-10-16', 'YYYY-MM-DD')
)

SELECT DISTINCT(C.CAR_ID), NVL2(A.CAR_ID, '대여중', '대여 가능') AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
LEFT OUTER JOIN AVAILABLE_CAR A
ON C.CAR_ID = A.CAR_ID
ORDER BY CAR_ID DESC;

