-- 2022년 10월 16일에 대여 중인 자동차인 경우 '대여중', 대여 중이지 않은 경우 '대여 가능' 표시
WITH A AS (
    SELECT DISTINCT(CAR_ID) CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE HISTORY_ID NOT IN (
        SELECT C.HISTORY_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
        WHERE C.END_DATE < TO_DATE('2022-10-16', 'YYYY-MM-dd') OR C.START_DATE > TO_DATE('2022-10-16', 'YYYY-MM-DD')
    )
)

SELECT DISTINCT(B.CAR_ID), 
    CASE WHEN A.CAR_ID IS NULL THEN '대여 가능'
        WHEN A.CAR_ID IS NOT NULL THEN '대여중'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
LEFT JOIN A
ON B.CAR_ID = A.CAR_ID
ORDER BY B.CAR_ID DESC;