-- 코드를 입력하세요
# 총매출을 기준으로 내림차순 정렬
# 총매출 = PRCE * 주문량
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * SUM(FO.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT FP INNER JOIN FOOD_ORDER FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID;