-- FOOD_PRODUCT : 식품 정보
-- FOOD_ORDER : 식품의 주문 정보
-- 생산일자가 2022년 5월인 상품들의 정보 조회
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (SUM(O.AMOUNT * P.PRICE)) TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE TO_CHAR(O.PRODUCE_DATE, 'YYYYMM') = '202205'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;
