WITH A AS (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
)
SELECT A.HOUR, COUNT(B.ANIMAL_ID) AS COUNT
FROM A 
LEFT OUTER JOIN ANIMAL_OUTS B 
ON A.HOUR = TO_CHAR(B.DATETIME, 'HH24')
GROUP BY A.HOUR
ORDER BY A.HOUR;