-- 0시부터 23시까지 각 시간대별로 입양이 몇 건 발생했는지 계산
WITH A AS (
    SELECT LEVEL - 1 HOUR
    FROM DUAL 
    CONNECT BY LEVEL <= 24
)

SELECT A.HOUR, COUNT(O.ANIMAL_ID) COUNT
FROM A
LEFT JOIN ANIMAL_OUTS O
ON A.HOUR = TO_NUMBER(TO_CHAR(O.DATETIME, 'HH24'))
GROUP BY A.HOUR
ORDER BY A.HOUR;

