-- 사원별 성과금 정보 조회
-- BONUS는 어떻게 계산?
WITH GR AS (SELECT EMP_NO, CASE 
        WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(SCORE) >= 80 THEN 'B'
        ELSE 'C' END AS GRADE
FROM HR_GRADE
GROUP BY EMP_NO
)

SELECT HE.EMP_NO, HE.EMP_NAME, GR.GRADE,
    CASE 
        WHEN GR.GRADE = 'S' THEN HE.SAL * 0.2
        WHEN GR.GRADE = 'A' THEN HE.SAL * 0.15
        WHEN GR.GRADE = 'B' THEN HE.SAL * 0.1
        ELSE 0 END AS BONUS
FROM HR_EMPLOYEES HE INNER JOIN GR 
ON HE.EMP_NO = GR.EMP_NO
ORDER BY HE.EMP_NO;