-- 사원별 성과금 정보 조회
-- 사번, 성명, 평가 등급, 성과금
WITH A AS (SELECT E.EMP_NO,
    CASE WHEN AVG(G.SCORE) >= 96 THEN 'S'
    WHEN AVG(G.SCORE) >= 90 THEN 'A'
    WHEN AVG(G.SCORE) >= 80 THEN 'B'
    ELSE 'C' END AS GRADE
FROM HR_EMPLOYEES E
JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
)

SELECT DISTINCT(E.EMP_NO), E.EMP_NAME, A.GRADE,
    CASE WHEN A.GRADE = 'S' THEN E.SAL * 0.2
    WHEN A.GRADE = 'A' THEN E.SAL * 0.15
    WHEN A.GRADE = 'B' THEN E.SAL * 0.1
    ELSE 0 END AS BONUS
FROM HR_EMPLOYEES E
JOIN A
ON E.EMP_NO = A.EMP_NO
ORDER BY E.EMP_NO



