SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR, count(animal_id) COUNT
FROM ANIMAL_OUTS
WHERE TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) BETWEEN 9 AND 19
GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
order by HOUR