-- 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들에 대해서
-- 해당 기간 동안의 월별 자동차 Id 별 총 대여 횟수 리스트를 출력

SELECT 
    TO_NUMBER(TO_CHAR(START_DATE, 'MM')) MONTH, 
    CAR_ID, 
    COUNT(HISTORY_ID) RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    CAR_ID IN (
    SELECT C2.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C2
    WHERE C2.START_DATE >= TO_DATE('2022-08', 'YYYY-MM') AND C2.START_DATE < TO_DATE('2022-11', 'YYYY-MM') 
    GROUP BY C2.CAR_ID
    HAVING COUNT(C2.HISTORY_ID) >= 5
) and (START_DATE >= TO_DATE('2022-08', 'YYYY-MM') AND START_DATE < TO_DATE('2022-11', 'YYYY-MM') )
GROUP BY TO_NUMBER(TO_CHAR(START_DATE, 'MM')), CAR_ID
HAVING COUNT(HISTORY_ID) > 0
ORDER BY MONTH, CAR_ID DESC;

