SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08'
  and TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10'
  and CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08'
          and TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10'
        GROUP BY CAR_ID
        HAVING COUNT(HISTORY_ID) >= 5
  )
GROUP BY TO_NUMBER(TO_CHAR(START_DATE, 'MM')), CAR_ID
ORDER BY MONTH, CAR_ID DESC;

