# Python or C# 스킬을 가진 개발자 정보 조회
SELECT DISTINCT(D.ID), D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D INNER JOIN SKILLCODES S
WHERE ((D.SKILL_CODE & S.CODE) = 1024 OR (D.SKILL_CODE & S.CODE) = 256) OR
(D.SKILL_CODE & S.CODE = 1024 AND D.SKILL_CODE & S.CODE = 256)
ORDER BY D.ID;