-- 10월에 대여를 시작한 기록이 있는 '세단' 종류의 자동차
SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
ON C.CAR_ID = R.CAR_ID
WHERE C.CAR_TYPE = '세단' and (TO_CHAR(R.START_DATE, 'MM') = '10') 
ORDER BY C.CAR_ID DESC;