-- HR_DEPARTMENT : 회사의 부서 정보
-- HR_EMPLOYEES : 회사의 사원 정보
-- HR_GRADE : 2022년 사원 평가 정보
-- 2022년도 한해 평가 점수가 가장 높은 사원 정보 조회
WITH SC AS (SELECT SUM(SCORE) AS SCORE, EMP_NO
FROM HR_GRADE
WHERE YEAR = '2022'
GROUP BY EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1)

SELECT SC.SCORE, SC.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES HE INNER JOIN SC
ON HE.EMP_NO = SC.EMP_NO;

