-- FIRST_HALF : 아이스크림 가게의 상반기 주문 정보
-- ICECREAM_INFO : 아이스크림 성분 정보
-- 상반기 동안 각 아이스크림 성분 타입과 성분 타입에 대한
-- 아이스크림 총주문량을 총주문량이 작은 순서대로 조회
SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF F
JOIN ICECREAM_INFO I
ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;