-- USED_GOODS_BOARD : 중고거래 게시판 정보
-- 2022년 10월 5일에 등록된 중고거래 게시물 정보 조회
SELECT 
  BOARD_ID, 
  WRITER_ID, 
  TITLE, 
  PRICE,
  CASE WHEN STATUS = 'SALE' THEN '판매중'
       WHEN STATUS = 'RESERVED' THEN '예약중'
       ELSE '거래완료'
  END AS STATUS
FROM USED_GOODS_BOARD
WHERE TO_CHAR(CREATED_DATE, 'YYYY-MM-DD') = '2022-10-05'
ORDER BY BOARD_ID DESC
