-- 2022년 1월의 카테고리 별 도서 판매량 합산
SELECT B.CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;