-- 평균 길이가 33cm 이상인 물고기들을 종류별로 분류하여 잡은 수, 최대 길이, 물고기의 종류를 출력
WITH A AS (
    SELECT ID, FISH_TYPE,
    CASE WHEN LENGTH IS NULL THEN 10
    ELSE LENGTH END AS LENGTH
    FROM FISH_INFO
)

SELECT COUNT(ID) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM A
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE;
