-- BOOK : 도서 정보
-- AUTHOR : 저자 정보
-- 경제 카테고리에 속하는 도서 정보 출력
SELECT 
  B.BOOK_ID, 
  A.AUTHOR_NAME, 
  TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE